version: '3.1'

services:

  drupal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
    restart: always

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
    restart: always
