FROM drupal:8-apache

RUN apt-get update && apt-get install -y --no-install-recommends git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

RUN curl https://drupalconsole.com/installer -L -o drupal.phar \
  && mv drupal.phar /usr/local/bin/drupal \
  && chmod +x /usr/local/bin/drupal

RUN composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader 
